[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/lighthouse"
  to = "/.netlify/functions/lighthouse"
  status = 200

[[redirects]]
  from = "/api/lighthouse-status"
  to = "/.netlify/functions/lighthouse-status"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["node-fetch"]

[functions.lighthouse]
  timeout = 30
  memory = 1024
  maxDuration = 30

[functions.lighthouse-status]
  timeout = 10
  memory = 256