[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/lighthouse"
  to = "/.netlify/functions/lighthouse"
  status = 200

[[redirects]]
  from = "/api/lighthouse-status"
  to = "/.netlify/functions/lighthouse-status"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200